name: Deploy U3A Child Theme to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy via SCP to AWS Lightsail
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "u3a-child"
        target: ${{ secrets.REMOTE_PATH }}
